In [1]:
import pandas as pd # Importing the pandas library
import numpy as np # Importing the numpy library

In [13]:
# This is the sample data consisting of 'Name', 'Laptops' and 'CGPA' of some students.

dict = {
    'Names':["Bindupautra Jyotibrat", "Lassi Horny Gills", "Horny Pig", "Ek Shit Juicy", "Arumeme Gogoi", "Sarvanash"],
    'Locations':["Jorhat, Assam", "New Delhi", "Allahabad, Uttar Pradesh", "Ramnagar, Dehradun", "Sivsagar, Assam", "Banaras, Uttar Pradesh"],
    'Laptops':["Lenovo Ideapad", "HP Victus", "Asus TUF A15", "Lenovo Legion", "Asus Vivobook", "Lenovo Ideapad"],
    'CGPA':[8.6, 7, 7.5, 9.02, 7.1, 7.5]
}

In [15]:
#Creating a Dataframe of the sample data.

df = pd.DataFrame(dict)

In [16]:
# Printing the Dataframe.

df

                   Names                 Locations         Laptops  CGPA
0  Bindupautra Jyotibrat             Jorhat, Assam  Lenovo Ideapad  8.60
1      Lassi Horny Gills                 New Delhi       HP Victus  7.00
2              Horny Pig  Allahabad, Uttar Pradesh    Asus TUF A15  7.50
3          Ek Shit Juicy        Ramnagar, Dehradun   Lenovo Legion  9.02
4          Arumeme Gogoi           Sivsagar, Assam   Asus Vivobook  7.10
5              Sarvanash    Banaras, Uttar Pradesh  Lenovo Ideapad  7.50

In [5]:
# Saving the Dataframe to .csv file.

df.to_csv('Location_and_Laptop.csv')

In [6]:
# This will save the Dataframe in another .csv file but without the default indexing.

df.to_csv('Location_and_Laptop_without_index.csv', index=False)

In [17]:
# This will print the Dataframe.

df

                   Names                 Locations         Laptops  CGPA
0  Bindupautra Jyotibrat             Jorhat, Assam  Lenovo Ideapad  8.60
1      Lassi Horny Gills                 New Delhi       HP Victus  7.00
2              Horny Pig  Allahabad, Uttar Pradesh    Asus TUF A15  7.50
3          Ek Shit Juicy        Ramnagar, Dehradun   Lenovo Legion  9.02
4          Arumeme Gogoi           Sivsagar, Assam   Asus Vivobook  7.10
5              Sarvanash    Banaras, Uttar Pradesh  Lenovo Ideapad  7.50

In [18]:
# This returns the top 5 elements of the .csv file. If there are less than 5 elements then, it returns all the elements.

df.head()

                   Names                 Locations         Laptops  CGPA
0  Bindupautra Jyotibrat             Jorhat, Assam  Lenovo Ideapad  8.60
1      Lassi Horny Gills                 New Delhi       HP Victus  7.00
2              Horny Pig  Allahabad, Uttar Pradesh    Asus TUF A15  7.50
3          Ek Shit Juicy        Ramnagar, Dehradun   Lenovo Legion  9.02
4          Arumeme Gogoi           Sivsagar, Assam   Asus Vivobook  7.10

In [19]:
# This returns the bottom 5 elements of the .csv file. If there are less than 5 elements then, it returns all the elements. 

df.tail()

               Names                 Locations         Laptops  CGPA
1  Lassi Horny Gills                 New Delhi       HP Victus  7.00
2          Horny Pig  Allahabad, Uttar Pradesh    Asus TUF A15  7.50
3      Ek Shit Juicy        Ramnagar, Dehradun   Lenovo Legion  9.02
4      Arumeme Gogoi           Sivsagar, Assam   Asus Vivobook  7.10
5          Sarvanash    Banaras, Uttar Pradesh  Lenovo Ideapad  7.50

In [20]:
# If we specify the number in the function then, it will return that number of elements from the top of the .csv file.

df.head(3)

                   Names                 Locations         Laptops  CGPA
0  Bindupautra Jyotibrat             Jorhat, Assam  Lenovo Ideapad   8.6
1      Lassi Horny Gills                 New Delhi       HP Victus   7.0
2              Horny Pig  Allahabad, Uttar Pradesh    Asus TUF A15   7.5

In [21]:
# If we specify the number in the function then, it will return that number of elements from the bottom of the .csv file.

df.tail(3)

           Names               Locations         Laptops  CGPA
3  Ek Shit Juicy      Ramnagar, Dehradun   Lenovo Legion  9.02
4  Arumeme Gogoi         Sivsagar, Assam   Asus Vivobook  7.10
5      Sarvanash  Banaras, Uttar Pradesh  Lenovo Ideapad  7.50

In [24]:
# This will display some specific information of the data in the .csv file.

df.describe()

           CGPA
count  6.000000
mean   7.786667
std    0.829136
min    7.000000
25%    7.200000
50%    7.500000
75%    8.325000
max    9.020000