In [1]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [3]:
# Generating the integers from 0 to 100 in 10 rows and 10 columns and also printing the dataframe.

df = pd.DataFrame(np.random.randint(0, 100, size=(10, 10)))
df

    0   1   2   3   4   5   6   7   8   9
0  72  16  32  87  55  30  10  88  87  67
1  29   7  58  17  11  54  98  15  65  55
2  60  62  31  84  19  18   4  34  30  77
3  87  92   3  89  60  20  86  29  67  29
4  70  92   2  89  46  93  14  73  45  26
5  12   2  68  16  37  11  88  95  82  19
6  66  79  82  53   4  70  77  92  48  18
7   4  56   0  49  72   3  24   8  10  11
8  11   1   9  50  43  94   5  34  39  45
9  60  23   0  79  27  80  51  62  26  89

In [12]:
# This function makes dataframe to an excel sheet.

df.to_excel('Excel_Sheet.xlsx')

In [14]:
# This function is used to read an excel sheet.

data = pd.read_excel('Excel_Sheet.xlsx')
data

   Unnamed: 0   0   1   2   3   4   5   6   7   8   9
0           0  72  16  32  87  55  30  10  88  87  67
1           1  29   7  58  17  11  54  98  15  65  55
2           2  60  62  31  84  19  18   4  34  30  77
3           3  87  92   3  89  60  20  86  29  67  29
4           4  70  92   2  89  46  93  14  73  45  26
5           5  12   2  68  16  37  11  88  95  82  19
6           6  66  79  82  53   4  70  77  92  48  18
7           7   4  56   0  49  72   3  24   8  10  11
8           8  11   1   9  50  43  94   5  34  39  45
9           9  60  23   0  79  27  80  51  62  26  89

In [16]:
# Using this function we can write in a particular sheet in an excel sheet.

data_1 = pd.read_excel('Excel_Sheet.xlsx', sheet_name='Sheet1')
data_1

   Unnamed: 0   0   1   2   3   4   5   6   7   8   9
0           0  72  16  32  87  55  30  10  88  87  67
1           1  29   7  58  17  11  54  98  15  65  55
2           2  60  62  31  84  19  18   4  34  30  77
3           3  87  92   3  89  60  20  86  29  67  29
4           4  70  92   2  89  46  93  14  73  45  26
5           5  12   2  68  16  37  11  88  95  82  19
6           6  66  79  82  53   4  70  77  92  48  18
7           7   4  56   0  49  72   3  24   8  10  11
8           8  11   1   9  50  43  94   5  34  39  45
9           9  60  23   0  79  27  80  51  62  26  89

In [18]:
# Generating another dataframe of integers from 100 to 200 in 10 rows and 10 columns.

df_2 = pd.DataFrame(np.random.randint(100, 200, size=(10, 10)))
df_2

     0    1    2    3    4    5    6    7    8    9
0  182  134  124  155  169  174  108  193  160  125
1  184  128  116  140  124  111  121  147  114  107
2  147  128  161  111  106  161  111  117  168  157
3  163  161  103  131  157  165  120  108  103  109
4  104  145  125  162  158  193  127  195  147  137
5  161  162  108  131  194  142  183  188  114  104
6  195  150  101  135  110  141  196  189  104  154
7  117  121  107  113  110  170  179  110  104  168
8  181  188  192  120  194  171  174  133  107  170
9  185  100  174  118  104  174  187  129  110  132

In [21]:
# We have copied the data and pasted in the excel sheet and then we are reading it that the data has changed in the sheet 2 of the excel sheet or not.

data_2 = pd.read_excel('Excel_Sheet.xlsx', sheet_name='Sheet2')
data_2

   Unnamed: 0    0    1    2    3    4    5    6    7    8    9
0           0  182  134  124  155  169  174  108  193  160  125
1           1  184  128  116  140  124  111  121  147  114  107
2           2  147  128  161  111  106  161  111  117  168  157
3           3  163  161  103  131  157  165  120  108  103  109
4           4  104  145  125  162  158  193  127  195  147  137
5           5  161  162  108  131  194  142  183  188  114  104
6           6  195  150  101  135  110  141  196  189  104  154
7           7  117  121  107  113  110  170  179  110  104  168
8           8  181  188  192  120  194  171  174  133  107  170
9           9  185  100  174  118  104  174  187  129  110  132

In [22]:
# Changing the data at index [0][0], but here we are changing the copy and not not implemented in the original excel sheet which located somewhere in the memory.

data_2.iloc[0, 0] = 1000
data_2

   Unnamed: 0    0    1    2    3    4    5    6    7    8    9
0        1000  182  134  124  155  169  174  108  193  160  125
1           1  184  128  116  140  124  111  121  147  114  107
2           2  147  128  161  111  106  161  111  117  168  157
3           3  163  161  103  131  157  165  120  108  103  109
4           4  104  145  125  162  158  193  127  195  147  137
5           5  161  162  108  131  194  142  183  188  114  104
6           6  195  150  101  135  110  141  196  189  104  154
7           7  117  121  107  113  110  170  179  110  104  168
8           8  181  188  192  120  194  171  174  133  107  170
9           9  185  100  174  118  104  174  187  129  110  132

In [23]:
# Using this function we are writing in the excel sheet the data we have changed in the copy of the excel sheet.

data_2.to_excel('Excel_Sheet.xlsx', sheet_name='Sheet2')