In [1]:
import pandas as pd # Importing the pandas library
import numpy as np # Importing the numpy library

In [2]:
# This is the sample data of Stations through which the trains passes and what is the total time taken to complete the destination.

railway = {
    'Station': ["Guwahati - Jorhat", "Dibrugarh - Guwahati", "Mariani - New Delhi"],
    'Train': ["Jana-Shatabdi", "Nagaland Express", "Rajdhani"],
    'Time': [8, 12, 36]
}

In [3]:
# Creating a Dataframe of the Data. A Dataframe is a collection of rows and columns in which we keep the data.

df = pd.DataFrame(railway)

In [4]:
df

                Station             Train  Time
0     Guwahati - Jorhat     Jana-Shatabdi     8
1  Dibrugarh - Guwahati  Nagaland Express    12
2   Mariani - New Delhi          Rajdhani    36

In [6]:
#Storing the Dataframe in a .csv file.

df.to_csv('railway.csv')

In [7]:
# read the .csv file and assigning it to a variable such that using that variable we can perform operations.

rail = pd.read_csv('railway.csv')

In [8]:
# This will return the data in the 'Time' column. 

rail['Time']

0     8
1    12
2    36
Name: Time, dtype: int64

In [9]:
# This will return the data of the default index of the .csv file. 

rail['Unnamed: 0']

0    0
1    1
2    2
Name: Unnamed: 0, dtype: int64

In [10]:
# This will return the data at the index 1 of the column 'Station'.

rail['Station'][1]

'Dibrugarh - Guwahati'

In [11]:
# This will change the data at the index 0 of the column 'Time'. The change is only on the outside like temporary and not saved in the .csv file. 

rail['Time'][0] = 7

C:\Users\gamin\AppData\Local\Temp\ipykernel_18268\353396999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rail['Time'][0] = 7

In [12]:
# Printing the content of the .csv file after changing the data.

rail

   Unnamed: 0               Station             Train  Time
0           0     Guwahati - Jorhat     Jana-Shatabdi     7
1           1  Dibrugarh - Guwahati  Nagaland Express    12
2           2   Mariani - New Delhi          Rajdhani    36

In [13]:
# After changing the data, saving it in the .csv file. Now, the changed data will be saved in the .csv file.

rail.to_csv('railway.csv')

In [16]:
# This will add a indexing layer to the pre existing indexing layer consisting of numbers.

rail.index = ['one', 'two', 'three']

In [17]:
rail

       Unnamed: 0               Station             Train  Time
one             0     Guwahati - Jorhat     Jana-Shatabdi     7
two             1  Dibrugarh - Guwahati  Nagaland Express    12
three           2   Mariani - New Delhi          Rajdhani    36

In [18]:
# Changing the data of the pre-indexing layer.

rail.index = ['ek', 'dui', 'tin']

In [19]:
# Printing the data after altering the data.

rail

     Unnamed: 0               Station             Train  Time
ek            0     Guwahati - Jorhat     Jana-Shatabdi     7
dui           1  Dibrugarh - Guwahati  Nagaland Express    12
tin           2   Mariani - New Delhi          Rajdhani    36