In [6]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [7]:
# Creating a Dataframe of random numbers with 100 rows and 5 columns.

dataframe = pd.DataFrame(np.random.rand(100, 5))

In [8]:
# Printing the Dataframe

dataframe

           0         1         2         3         4
0   0.359361  0.882502  0.175289  0.504480  0.878178
1   0.511645  0.527173  0.463580  0.172921  0.961464
2   0.383493  0.278786  0.734212  0.594326  0.608890
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
..       ...       ...       ...       ...       ...
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

[100 rows x 5 columns]

In [9]:
# this displays a specific part of the dataframe.

dataframe.loc[[10, 20], [1, 2]]

           1         2
10  0.545465  0.261281
20  0.361195  0.651072

In [10]:
# This shows all the columns of the dataframe but some specific rows.

dataframe.loc[[10, 20],:]

           0         1         2         3         4
10  0.252715  0.545465  0.261281  0.931007  0.101236
20  0.032984  0.361195  0.651072  0.811481  0.820001

In [11]:
# This shows all the rows of the dataframe but some specific columns.

dataframe.loc[:,[1,2]]

           1         2
0   0.882502  0.175289
1   0.527173  0.463580
2   0.278786  0.734212
3   0.109729  0.114678
4   0.496473  0.113392
..       ...       ...
95  0.344233  0.017012
96  0.760426  0.622184
97  0.564795  0.172938
98  0.016850  0.200402
99  0.481383  0.303840

[100 rows x 2 columns]

In [16]:
# This gives all the rows along with their columns where the index is 0 for the row and the value of the data stored in that location of the table is less than 0.5. It is complex database query.

dataframe.loc[(dataframe[0] < 0.5)]

           0         1         2         3         4
0   0.359361  0.882502  0.175289  0.504480  0.878178
2   0.383493  0.278786  0.734212  0.594326  0.608890
4   0.427871  0.496473  0.113392  0.457887  0.529089
5   0.054745  0.374227  0.064212  0.698444  0.958499
6   0.020835  0.762644  0.866600  0.438742  0.526921
7   0.367215  0.082053  0.686345  0.006993  0.971015
8   0.170645  0.490655  0.726935  0.355941  0.165311
9   0.242023  0.623553  0.145912  0.415161  0.518278
10  0.252715  0.545465  0.261281  0.931007  0.101236
11  0.213497  0.053995  0.945158  0.670984  0.547081
18  0.197824  0.221363  0.797175  0.317293  0.291129
19  0.214637  0.813806  0.707865  0.323200  0.366466
20  0.032984  0.361195  0.651072  0.811481  0.820001
24  0.445481  0.614395  0.883523  0.880571  0.940741
25  0.417418  0.181724  0.952317  0.259001  0.081199
29  0.135073  0.453449  0.554305  0.932784  0.829503
30  0.131793  0.875431  0.706562  0.533483  0.060314
34  0.248499  0.367758  0.192629  0.249776  0.792341
36  0.392474  0.121378  0.092389  0.818921  0.993031
38  0.472747  0.067363  0.682353  0.294121  0.026610
44  0.381857  0.433591  0.354198  0.392468  0.743953
45  0.076201  0.159268  0.375957  0.658711  0.784685
46  0.258658  0.616626  0.528380  0.068251  0.882221
49  0.463476  0.362926  0.560064  0.613388  0.079027
52  0.082962  0.766630  0.212206  0.140046  0.694732
53  0.452942  0.486158  0.212702  0.890485  0.207850
55  0.404385  0.290942  0.486896  0.355254  0.425712
57  0.097352  0.619124  0.282615  0.843290  0.909579
58  0.432246  0.288852  0.879637  0.609730  0.741249
60  0.366161  0.656106  0.794099  0.007556  0.378045
62  0.468067  0.134230  0.143054  0.334048  0.287682
66  0.048498  0.573803  0.413701  0.021539  0.742753
67  0.234719  0.536922  0.415994  0.101335  0.447650
68  0.236264  0.100086  0.875104  0.669335  0.190432
69  0.250728  0.688549  0.529239  0.131470  0.734687
71  0.406539  0.418178  0.619184  0.610495  0.050821
72  0.043609  0.296996  0.626444  0.189906  0.228697
74  0.294489  0.135774  0.515074  0.213123  0.180950
75  0.025486  0.447365  0.931606  0.961569  0.117039
77  0.244707  0.722004  0.029810  0.036276  0.817781
78  0.206283  0.752465  0.967002  0.767154  0.819713
83  0.171844  0.779035  0.452584  0.310061  0.263014
85  0.054888  0.636784  0.069228  0.959126  0.078229
86  0.363831  0.898181  0.806446  0.135448  0.854544
91  0.030821  0.527208  0.844842  0.407062  0.478903
93  0.240444  0.332247  0.539041  0.076858  0.674427
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

In [17]:
# If the index of the table is something else like a alphabet then I want to access a particular element from the table then I have to give the specific index and I cannot use number if the index is not a number. This is the case for using .loc function, but we can use numbers even if the index is not a number using the .iloc function.

dataframe.iloc[0,4]

np.float64(0.8781778834720873)

In [18]:
# We have changed the indexing of the columns from numbers to alphabets.

dataframe.columns = list('ABCDE')

In [19]:
# Printing the top five elements after changing the indexing of the columns.

dataframe.head()

          A         B         C         D         E
0  0.359361  0.882502  0.175289  0.504480  0.878178
1  0.511645  0.527173  0.463580  0.172921  0.961464
2  0.383493  0.278786  0.734212  0.594326  0.608890
3  0.618114  0.109729  0.114678  0.943649  0.731567
4  0.427871  0.496473  0.113392  0.457887  0.529089

In [20]:
# Even after changing the index from numbers to alphabets we can still use numbers to access elements using the .iloc function.

dataframe.iloc[[0,1],[1,0]]

          B         A
0  0.882502  0.359361
1  0.527173  0.511645

In [21]:
# We are dropping the row of index 0, but this is temporarily done and original table is not changed in the memory.

dataframe.drop([0])

           A         B         C         D         E
1   0.511645  0.527173  0.463580  0.172921  0.961464
2   0.383493  0.278786  0.734212  0.594326  0.608890
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
5   0.054745  0.374227  0.064212  0.698444  0.958499
..       ...       ...       ...       ...       ...
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

[99 rows x 5 columns]

In [22]:
# Printing the dataframe for testing the function of drop for row and we can see the drop function did not changed and worked as expected. It had changed the original tabel in the memory location if we have added a specific syntax to it.

dataframe

           A         B         C         D         E
0   0.359361  0.882502  0.175289  0.504480  0.878178
1   0.511645  0.527173  0.463580  0.172921  0.961464
2   0.383493  0.278786  0.734212  0.594326  0.608890
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
..       ...       ...       ...       ...       ...
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

[100 rows x 5 columns]

In [23]:
# This is the additional syntax which the changes the table in the memory location permanently.

dataframe = dataframe.drop([0])

In [24]:
# Printing the database to check for the expected functionality.

dataframe

           A         B         C         D         E
1   0.511645  0.527173  0.463580  0.172921  0.961464
2   0.383493  0.278786  0.734212  0.594326  0.608890
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
5   0.054745  0.374227  0.064212  0.698444  0.958499
..       ...       ...       ...       ...       ...
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

[99 rows x 5 columns]

In [30]:
# This is another way to change the data in the table in the memory location permanently.

dataframe.drop([2], inplace=True)

In [31]:
dataframe.head(4)

          A         B         C         D         E
3  0.618114  0.109729  0.114678  0.943649  0.731567
4  0.427871  0.496473  0.113392  0.457887  0.529089
5  0.054745  0.374227  0.064212  0.698444  0.958499
6  0.020835  0.762644  0.866600  0.438742  0.526921

In [40]:
# This is a complex query of an database which we are using here. This will print all the columns but not all the rows. This will check for the numbers in the columns 'C' and columns 'E' for numbers which are less than 0.9 and greater than 0.5 respectively and return those specific rows in which the specific index along with the column is present and print it.

dataframe.loc[(dataframe['C'] < 0.9) & (dataframe['E'] > 0.5)]

           A         B         C         D         E
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
5   0.054745  0.374227  0.064212  0.698444  0.958499
6   0.020835  0.762644  0.866600  0.438742  0.526921
7   0.367215  0.082053  0.686345  0.006993  0.971015
9   0.242023  0.623553  0.145912  0.415161  0.518278
13  0.577718  0.154029  0.824399  0.259246  0.999806
20  0.032984  0.361195  0.651072  0.811481  0.820001
22  0.751723  0.752570  0.456794  0.706291  0.544512
24  0.445481  0.614395  0.883523  0.880571  0.940741
26  0.584068  0.542615  0.586080  0.107124  0.997186
27  0.562287  0.170294  0.010380  0.664795  0.774726
29  0.135073  0.453449  0.554305  0.932784  0.829503
32  0.577602  0.820190  0.285502  0.046025  0.988425
33  0.807378  0.294550  0.398252  0.203279  0.833956
34  0.248499  0.367758  0.192629  0.249776  0.792341
36  0.392474  0.121378  0.092389  0.818921  0.993031
39  0.670528  0.970143  0.062439  0.636008  0.679228
41  0.546101  0.444237  0.169420  0.656102  0.814219
42  0.656573  0.314899  0.856499  0.036258  0.890654
44  0.381857  0.433591  0.354198  0.392468  0.743953
45  0.076201  0.159268  0.375957  0.658711  0.784685
46  0.258658  0.616626  0.528380  0.068251  0.882221
47  0.921071  0.221129  0.748931  0.076701  0.603702
48  0.568923  0.673863  0.289382  0.292754  0.641528
52  0.082962  0.766630  0.212206  0.140046  0.694732
56  0.566752  0.355342  0.150686  0.050633  0.998359
57  0.097352  0.619124  0.282615  0.843290  0.909579
58  0.432246  0.288852  0.879637  0.609730  0.741249
61  0.984680  0.824953  0.420978  0.652658  0.643631
63  0.685878  0.865435  0.680466  0.870059  0.699250
66  0.048498  0.573803  0.413701  0.021539  0.742753
69  0.250728  0.688549  0.529239  0.131470  0.734687
70  0.517776  0.388438  0.532873  0.223460  0.893228
73  0.808901  0.837253  0.395277  0.728439  0.517554
76  0.942156  0.014136  0.844086  0.965153  0.998901
77  0.244707  0.722004  0.029810  0.036276  0.817781
81  0.536162  0.734161  0.662487  0.652417  0.609928
82  0.783761  0.440553  0.622520  0.487022  0.640478
86  0.363831  0.898181  0.806446  0.135448  0.854544
87  0.950832  0.946729  0.680897  0.358125  0.599569
92  0.932852  0.538207  0.685501  0.857264  0.759089
93  0.240444  0.332247  0.539041  0.076858  0.674427
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
98  0.159363  0.016850  0.200402  0.987672  0.741778

In [41]:
# Printing the top five rows along with their columns to check for the indexin of the rows.

dataframe.head()

          A         B         C         D         E
3  0.618114  0.109729  0.114678  0.943649  0.731567
4  0.427871  0.496473  0.113392  0.457887  0.529089
5  0.054745  0.374227  0.064212  0.698444  0.958499
6  0.020835  0.762644  0.866600  0.438742  0.526921
7  0.367215  0.082053  0.686345  0.006993  0.971015

In [42]:
# This resets the indexing of the rows to 0 to ... instead of 3 to ...(which is in this case), but the case is it does it temporarily and there is no change in the original dataframe located in the memory.

dataframe.reset_index()

    index         A         B         C         D         E
0       3  0.618114  0.109729  0.114678  0.943649  0.731567
1       4  0.427871  0.496473  0.113392  0.457887  0.529089
2       5  0.054745  0.374227  0.064212  0.698444  0.958499
3       6  0.020835  0.762644  0.866600  0.438742  0.526921
4       7  0.367215  0.082053  0.686345  0.006993  0.971015
..    ...       ...       ...       ...       ...       ...
92     95  0.597712  0.344233  0.017012  0.335141  0.740804
93     96  0.860908  0.760426  0.622184  0.598161  0.755601
94     97  0.002772  0.564795  0.172938  0.476008  0.049592
95     98  0.159363  0.016850  0.200402  0.987672  0.741778
96     99  0.005097  0.481383  0.303840  0.342270  0.484828

[97 rows x 6 columns]

In [43]:
# Checking for the indexing of the row that it has changed or not.

dataframe

           A         B         C         D         E
3   0.618114  0.109729  0.114678  0.943649  0.731567
4   0.427871  0.496473  0.113392  0.457887  0.529089
5   0.054745  0.374227  0.064212  0.698444  0.958499
6   0.020835  0.762644  0.866600  0.438742  0.526921
7   0.367215  0.082053  0.686345  0.006993  0.971015
..       ...       ...       ...       ...       ...
95  0.597712  0.344233  0.017012  0.335141  0.740804
96  0.860908  0.760426  0.622184  0.598161  0.755601
97  0.002772  0.564795  0.172938  0.476008  0.049592
98  0.159363  0.016850  0.200402  0.987672  0.741778
99  0.005097  0.481383  0.303840  0.342270  0.484828

[97 rows x 5 columns]

In [ ]:
# This will change the original dataframe as we have added the argument 'inplace' and the 'drop' argument removes the extra column along side the new indexing column. This extra column shows the original indexing of the dataframe before the change of the indexing. Also we can change the original dataframe using the old style like this 'dataframe = ...'. Also, it only changes the indexing of the rows and not the columns.

dataframe.reset_index(drop=True, inplace=True)

In [46]:
# Printing the top five rows of the dataframe to check the intended behaviour of the 'reset_index' function of the dataframe.

dataframe.head()

          A         B         C         D         E
0  0.618114  0.109729  0.114678  0.943649  0.731567
1  0.427871  0.496473  0.113392  0.457887  0.529089
2  0.054745  0.374227  0.064212  0.698444  0.958499
3  0.020835  0.762644  0.866600  0.438742  0.526921
4  0.367215  0.082053  0.686345  0.006993  0.971015