In [1]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [10]:
# Creating a Dataframe of random numbers with 500 rows and 10 columns.

dataframe_1 = pd.DataFrame(np. random.rand(500, 10))

In [21]:
# Printing the Dataframe

dataframe_1

,0,1,2,3,4,5,6,7,8,9
0,0.491192,0.081438,0.949768,0.251380,0.758934,0.442939,0.939416,0.938830,0.532043,0.889528
1,0.587898,0.299061,0.207036,0.760721,0.949992,0.415078,0.979995,0.477288,0.723593,0.276340
2,0.569427,0.582618,0.790273,0.649981,0.125582,0.610175,0.146824,0.322537,0.205996,0.446608
3,0.640342,0.108810,0.779049,0.924028,0.928866,0.935150,0.760458,0.329689,0.115535,0.986821
4,0.254021,0.278465,0.446758,0.469820,0.408947,0.728870,0.961935,0.830135,0.343560,0.849346
...,...,...,...,...,...,...,...,...,...,...
495,0.813368,0.152008,0.300713,0.195224,0.224295,0.528841,0.566989,0.763698,0.335304,0.065245
496,0.840323,0.909241,0.421025,0.660735,0.261443,0.360050,0.486099,0.628500,0.614764,0.866158
497,0.310416,0.189556,0.486617,0.288456,0.597730,0.001773,0.709624,0.256548,0.705733,0.692256
498,0.202656,0.590929,0.922566,0.191540,0.903591,0.000407,0.173215,0.144201,0.516605,0.851626
499,0.127859,0.127942,0.987330,0.584003,0.407377,0.002558,0.664281,0.619730,0.515175,0.539601

In [22]:
# Creating a Dataframe of random numbers with 500 rows and 10 columns.

dataframe_2 = pd.DataFrame(np.random.random((500, 10)))

In [12]:
# Printing the Dataframe

dataframe_2

,0,1,2,3,4,5,6,7,8,9
0,0.436506,0.449203,0.806485,0.789453,0.650132,0.954421,0.954570,0.138758,0.537150,0.492708
1,0.931393,0.587692,0.048433,0.099312,0.404984,0.144856,0.232420,0.781536,0.287873,0.804482
2,0.546342,0.540023,0.829696,0.399398,0.785398,0.338994,0.568035,0.626091,0.104762,0.802949
3,0.596509,0.554023,0.653980,0.856510,0.248247,0.356538,0.786711,0.307096,0.147188,0.036527
4,0.813892,0.620503,0.610994,0.417048,0.097493,0.821200,0.135750,0.508706,0.076263,0.345525
...,...,...,...,...,...,...,...,...,...,...
495,0.593288,0.367052,0.020566,0.823326,0.669373,0.116935,0.377903,0.731575,0.539381,0.038512
496,0.255138,0.366447,0.394711,0.955964,0.048232,0.991598,0.617016,0.688940,0.822246,0.211833
497,0.383374,0.661104,0.892761,0.323960,0.331037,0.754344,0.983720,0.518415,0.218681,0.895460
498,0.285275,0.896154,0.725286,0.021066,0.381279,0.729465,0.415409,0.405805,0.578694,0.806860
499,0.026157,0.266297,0.416335,0.014368,0.721378,0.094495,0.405469,0.904789,0.921097,0.295133

In [13]:
# Sorting the Dataframe on the basis of index. Here axis means columns and if ascending is True it means that indexing will be like 0 to ... and if false then vice versa. If axis is 1 then we sort the columns and if not then we do not sort and sorting is done using the 'ascending'.

dataframe_1.sort_index(axis=0, ascending=False)

,0,1,2,3,4,5,6,7,8,9
499,0.127859,0.127942,0.987330,0.584003,0.407377,0.002558,0.664281,0.619730,0.515175,0.539601
498,0.202656,0.590929,0.922566,0.191540,0.903591,0.000407,0.173215,0.144201,0.516605,0.851626
497,0.310416,0.189556,0.486617,0.288456,0.597730,0.001773,0.709624,0.256548,0.705733,0.692256
496,0.840323,0.909241,0.421025,0.660735,0.261443,0.360050,0.486099,0.628500,0.614764,0.866158
495,0.813368,0.152008,0.300713,0.195224,0.224295,0.528841,0.566989,0.763698,0.335304,0.065245
...,...,...,...,...,...,...,...,...,...,...
4,0.254021,0.278465,0.446758,0.469820,0.408947,0.728870,0.961935,0.830135,0.343560,0.849346
3,0.640342,0.108810,0.779049,0.924028,0.928866,0.935150,0.760458,0.329689,0.115535,0.986821
2,0.569427,0.582618,0.790273,0.649981,0.125582,0.610175,0.146824,0.322537,0.205996,0.446608
1,0.587898,0.299061,0.207036,0.760721,0.949992,0.415078,0.979995,0.477288,0.723593,0.276340
0,0.491192,0.081438,0.949768,0.251380,0.758934,0.442939,0.939416,0.938830,0.532043,0.889528

In [23]:
# Explanation above☝️

dataframe_1.sort_index(axis=1, ascending=False)

,9,8,7,6,5,4,3,2,1,0
0,0.889528,0.532043,0.938830,0.939416,0.442939,0.758934,0.251380,0.949768,0.081438,0.491192
1,0.276340,0.723593,0.477288,0.979995,0.415078,0.949992,0.760721,0.207036,0.299061,0.587898
2,0.446608,0.205996,0.322537,0.146824,0.610175,0.125582,0.649981,0.790273,0.582618,0.569427
3,0.986821,0.115535,0.329689,0.760458,0.935150,0.928866,0.924028,0.779049,0.108810,0.640342
4,0.849346,0.343560,0.830135,0.961935,0.728870,0.408947,0.469820,0.446758,0.278465,0.254021
...,...,...,...,...,...,...,...,...,...,...
495,0.065245,0.335304,0.763698,0.566989,0.528841,0.224295,0.195224,0.300713,0.152008,0.813368
496,0.866158,0.614764,0.628500,0.486099,0.360050,0.261443,0.660735,0.421025,0.909241,0.840323
497,0.692256,0.705733,0.256548,0.709624,0.001773,0.597730,0.288456,0.486617,0.189556,0.310416
498,0.851626,0.516605,0.144201,0.173215,0.000407,0.903591,0.191540,0.922566,0.590929,0.202656
499,0.539601,0.515175,0.619730,0.664281,0.002558,0.407377,0.584003,0.987330,0.127942,0.127859

In [16]:
# It is not copying. It is called as making a view of the Dataset. It is like making a pointer of the original dataset. The dataset is in the original memory location and it makes a pointer of it like we change the view then the original will also change.

dataframe = dataframe_2

In [17]:
# It prints the series of the Dataframe which is the [0] index series for this case.

dataframe[0]

0      0.436506
1      0.931393
2      0.546342
3      0.596509
4      0.813892
         ...
495    0.593288
496    0.255138
497    0.383374
498    0.285275
499    0.026157
Name: 0, Length: 500, dtype: float64

In [19]:
# Changing the data at the index[0][0] to "Hello World".
dataframe[0][0] = "Hello World"

C:\Users\gamin\AppData\Local\Temp\ipykernel_2380\1318300288.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Hello World' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataframe[0][0] = "Hello World"

In [20]:
# Printing the Dataframe.

dataframe

,0,1,2,3,4,5,6,7,8,9
0,Hello World,0.449203,0.806485,0.789453,0.650132,0.954421,0.954570,0.138758,0.537150,0.492708
1,0.931393,0.587692,0.048433,0.099312,0.404984,0.144856,0.232420,0.781536,0.287873,0.804482
2,0.546342,0.540023,0.829696,0.399398,0.785398,0.338994,0.568035,0.626091,0.104762,0.802949
3,0.596509,0.554023,0.653980,0.856510,0.248247,0.356538,0.786711,0.307096,0.147188,0.036527
4,0.813892,0.620503,0.610994,0.417048,0.097493,0.821200,0.135750,0.508706,0.076263,0.345525
...,...,...,...,...,...,...,...,...,...,...
495,0.593288,0.367052,0.020566,0.823326,0.669373,0.116935,0.377903,0.731575,0.539381,0.038512
496,0.255138,0.366447,0.394711,0.955964,0.048232,0.991598,0.617016,0.688940,0.822246,0.211833
497,0.383374,0.661104,0.892761,0.323960,0.331037,0.754344,0.983720,0.518415,0.218681,0.895460
498,0.285275,0.896154,0.725286,0.021066,0.381279,0.729465,0.415409,0.405805,0.578694,0.806860
499,0.026157,0.266297,0.416335,0.014368,0.721378,0.094495,0.405469,0.904789,0.921097,0.295133

In [24]:
# This means a copy and not a pointer like the data is stored in 2 different locations one is the copy and another one is original.

dataframe_copy = dataframe_2.copy()

In [25]:
# we have changed the data at the index [0][0] of the copy of the dataframe and not the original dataframe.

dataframe_copy[0][0] = 12345

C:\Users\gamin\AppData\Local\Temp\ipykernel_2380\1355483313.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe_copy[0][0] = 12345

In [26]:
# Printing the copied dataframe.

dataframe_copy

,0,1,2,3,4,5,6,7,8,9
0,12345.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346
...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254

In [27]:
# Printing the dataframe and we can notice that the data at the index [0][0] has not changed that means the data has only been changed of the copy dataframe.

dataframe_2

,0,1,2,3,4,5,6,7,8,9
0,0.184678,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346
...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254

In [28]:
# Changing the data at the index [0][0] using the loc function.

dataframe_2.loc[0, 0] = 6789

In [29]:
# Printing the Dataframe.

dataframe_2

,0,1,2,3,4,5,6,7,8,9
0,6789.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346
...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254

In [31]:
# This changes the default index of the columns which are numbers to Alphabets.

dataframe_2.columns = list('ABCDEFGHIJ')

In [32]:
# This will print the top four rows and along with their respective columns.

dataframe_2.head(4)

,A,B,C,D,E,F,G,H,I,J
0,6789.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796

In [36]:
# Changing the data at the index [0][0] using the loc function.

dataframe_2.loc[0, 0] = 1357

In [37]:
# Printing the Dataframe.

dataframe_2

,A,B,C,D,E,F,G,H,I,J,0
0,6789.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555,1357.0
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767,NaN
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688,NaN
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796,NaN
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346,NaN
...,...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708,NaN
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227,NaN
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463,NaN
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054,NaN
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254,NaN

In [41]:
# Changing the data at the index [0][0] using the loc function.

dataframe_2.loc[0, 'A'] = 2468

In [42]:
# Printing the Dataframe.

dataframe_2

,A,B,C,D,E,F,G,H,I,J,0,"(0, A)"
0,2468.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555,1357.0,2468
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767,NaN,2468
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688,NaN,2468
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796,NaN,2468
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346,NaN,2468
...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708,NaN,2468
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227,NaN,2468
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463,NaN,2468
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054,NaN,2468
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254,NaN,2468

In [49]:
# This will remove the '0' column but it will be temporarily that is there will be no effect in the memory location.

dataframe_2.drop(0, axis=1)

In [50]:
# Printing the Dataframe.

dataframe_2

,A,B,C,D,E,F,G,H,I,J,"(0, A)"
0,2468.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555,2468
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767,2468
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688,2468
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796,2468
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346,2468
...,...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708,2468
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227,2468
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463,2468
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054,2468
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254,2468

In [ ]:
# This will remove the '0' column but it will be permanent that is there will be full effect in the memory location.

dataframe_2 = dataframe_2.drop(0, axis=1)

In [51]:
# This will remove the '(0, 'A')' column but it will be permanent that is there will be full effect in the memory location. If we need to do the same in the rows section then we need select '0' in the axis section.

dataframe_2 = dataframe_2.drop((0, 'A'), axis=1)

In [52]:
# Printing the Dataframe.

dataframe_2

,A,B,C,D,E,F,G,H,I,J
0,2468.000000,0.415017,0.843127,0.932885,0.277407,0.655463,0.576358,0.988282,0.059818,0.678555
1,0.939306,0.706394,0.886203,0.709310,0.039545,0.325126,0.266037,0.085842,0.585611,0.258767
2,0.224176,0.171473,0.246875,0.654000,0.790632,0.803264,0.336331,0.859821,0.201326,0.686688
3,0.528298,0.734450,0.213743,0.732951,0.279369,0.305911,0.548695,0.601976,0.967882,0.923796
4,0.226641,0.480661,0.726674,0.083935,0.777373,0.521160,0.554665,0.787845,0.369196,0.549346
...,...,...,...,...,...,...,...,...,...,...
495,0.445744,0.107915,0.010662,0.662550,0.696229,0.499564,0.029966,0.132215,0.927621,0.995708
496,0.122647,0.811358,0.735981,0.041031,0.116955,0.101126,0.819964,0.912614,0.509478,0.894227
497,0.232869,0.023336,0.094940,0.489597,0.448774,0.907141,0.823196,0.181478,0.484795,0.680463
498,0.478437,0.492179,0.051173,0.757198,0.575195,0.808574,0.530683,0.558782,0.862973,0.715054
499,0.158613,0.813921,0.469426,0.681662,0.750695,0.744011,0.309347,0.474135,0.948885,0.108254