In [1]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [2]:
# Made a Dataframe of random numbers between 0 and 1 of 10 rows and 10 columns.

dataframe = pd.DataFrame(np.random.rand(10, 10))

In [3]:
# Printing the top five rows along with all the respective columns.

dataframe.head()

,0,1,2,3,4,5,6,7,8,9
0,0.645395,0.000077,0.657989,0.669542,0.593531,0.315880,0.891455,0.249483,0.503846,0.921246
1,0.394972,0.546646,0.757059,0.683072,0.513372,0.579928,0.579491,0.674813,0.070536,0.188389
2,0.695086,0.048871,0.091834,0.723416,0.948323,0.379226,0.925800,0.737797,0.378184,0.403385
3,0.214543,0.807769,0.258646,0.583949,0.281062,0.663976,0.240383,0.817235,0.549483,0.386702
4,0.403172,0.853156,0.466439,0.819643,0.088094,0.328713,0.034653,0.330447,0.136276,0.755716

In [4]:
# Using this way can change all the values of the column of index '0' to None but, it is not preferred in normally because when we work on real datasets then sometimes the code becomes to long to detect the variable we are working on is a copy or making a view so while writting code with functions and working with dataset and we need to manipulate the dataset we must use .loc function or .iloc function.

dataframe[0] = None
dataframe

,0,1,2,3,4,5,6,7,8,9
0,None,0.000077,0.657989,0.669542,0.593531,0.315880,0.891455,0.249483,0.503846,0.921246
1,None,0.546646,0.757059,0.683072,0.513372,0.579928,0.579491,0.674813,0.070536,0.188389
2,None,0.048871,0.091834,0.723416,0.948323,0.379226,0.925800,0.737797,0.378184,0.403385
3,None,0.807769,0.258646,0.583949,0.281062,0.663976,0.240383,0.817235,0.549483,0.386702
4,None,0.853156,0.466439,0.819643,0.088094,0.328713,0.034653,0.330447,0.136276,0.755716
5,None,0.196969,0.446357,0.901947,0.362726,0.295458,0.720250,0.296459,0.184290,0.670865
6,None,0.828856,0.065206,0.556674,0.707910,0.007487,0.804831,0.018958,0.892380,0.558542
7,None,0.070975,0.755778,0.138892,0.062491,0.070387,0.311452,0.769691,0.506504,0.344549
8,None,0.064536,0.807652,0.081870,0.927662,0.188190,0.889332,0.792685,0.902167,0.783856
9,None,0.325331,0.082158,0.383066,0.000058,0.140846,0.608110,0.388889,0.532038,0.921812

In [5]:
# This function checks which values in the dataset is with null data type which is a boolean data type.

dataframe.isnull()

      0      1      2      3      4      5      6      7      8      9
0  True  False  False  False  False  False  False  False  False  False
1  True  False  False  False  False  False  False  False  False  False
2  True  False  False  False  False  False  False  False  False  False
3  True  False  False  False  False  False  False  False  False  False
4  True  False  False  False  False  False  False  False  False  False
5  True  False  False  False  False  False  False  False  False  False
6  True  False  False  False  False  False  False  False  False  False
7  True  False  False  False  False  False  False  False  False  False
8  True  False  False  False  False  False  False  False  False  False
9  True  False  False  False  False  False  False  False  False  False

In [10]:
# We are manipulating the dataset using the .loc function.

dataframe.loc[:,[0]] = 56
dataframe.isnull()

       0      1      2      3      4      5      6      7      8      9
0  False  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False  False  False  False
5  False  False  False  False  False  False  False  False  False  False
6  False  False  False  False  False  False  False  False  False  False
7  False  False  False  False  False  False  False  False  False  False
8  False  False  False  False  False  False  False  False  False  False
9  False  False  False  False  False  False  False  False  False  False

In [41]:
# Creating a Dataframe consisting of 'names', 'toy' and 'born'.

df = pd.DataFrame({"name": ['Alfred', 'batman', 'Alfred'],
                        "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                        "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                        pd.NaT]})
df

     name        toy       born
0  Alfred        NaN        NaT
1  batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [12]:
# This function removes any row which consist of the word "na" in any case (upper case or lower case).

df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [13]:
# This argument explicitly removes the rows which consists of the word "na".

df.dropna(axis="rows")

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [14]:
# Printing the dataframe.

df

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [16]:
# This argument explicitly removes the columns which consists of the word "na".

df.dropna(axis="columns")

       name
0    Alfred
1    Batman
2  Catwoman

In [28]:
# This removes only those rows which has all the elements consisting of the word "na" in a way or the other.

df.dropna(how="all")

       name        toy       born
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [32]:
# This argument any rows whose any element consists of the word "na" in a way or the other. But, in this case we choose to remove the columns explicitly by writing the argument 'axis=1', normally by default it removes the rows and not columns. 

df.dropna(how="any", axis=1)

       name
0    Alfred
1    Batman
2  Catwoman

In [43]:
df.drop_duplicates(subset='name')

     name        toy       born
0  Alfred        NaN        NaT
1  batman  Batmobile 1940-04-25

In [42]:
df.drop_duplicates(subset='name', keep='last')

     name        toy       born
1  batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [44]:
df.drop_duplicates(subset='name', keep=False)

     name        toy       born
1  batman  Batmobile 1940-04-25